# Generated by Django 6.0.5 on 2026-06-26 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('content', models.TextField()),
                ('mood', models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('anxious', 'Anxious'), ('excited', 'Excited'), ('lonely', 'Lonely'), ('peaceful', 'Peaceful'), ('confused', 'Confused'), ('grateful', 'Grateful'), ('numb', 'Numb'), ('hopeful', 'Hopeful'), ('frustrated', 'Frustrated'), ('melancholic', 'Melancholic'), ('content', 'Content'), ('overwhelmed', 'Overwhelmed'), ('other', 'Other')], default='other', max_length=20)),
                ('narrative_thread', models.TextField(blank=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('edited_content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
