# Generated by Django 6.0.5 on 2026-05-19 11:38

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('memory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384)),
                ('memory_class', models.CharField(choices=[('identity', 'Identity'), ('preference', 'Preference'), ('goal', 'Goal'), ('relationship', 'Relationship'), ('experience', 'Experience'), ('knowledge', 'Knowledge'), ('emotion', 'Emotion'), ('habit', 'Habit'), ('system', 'System')], default='experience', max_length=30)),
                ('importance_score', models.FloatField(default=0.5)),
                ('priority_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('is_ultimate', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('confidence_score', models.FloatField(default=1.0)),
                ('retrieval_count', models.IntegerField(default=0)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('source_message', models.TextField(blank=True, null=True)),
                ('summarized_content', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_memory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='memory.memory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='memory_memo_user_id_19f84a_idx'), models.Index(fields=['memory_class'], name='memory_memo_memory__042a0d_idx'), models.Index(fields=['is_ultimate'], name='memory_memo_is_ulti_25ec9a_idx'), models.Index(fields=['priority_level'], name='memory_memo_priorit_c322e1_idx'), models.Index(fields=['importance_score'], name='memory_memo_importa_a82548_idx')],
            },
        ),
    ]
